services:
  app:
    build: ./app
    container_name: dummy-app
    volumes:
      - ./fluentbit/logs:/fluentbit/logs

  fluentbit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluentbit/logs:/fluentbit/logs
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf